# Generated by Django 4.1.2 on 2022-10-24 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'incident_targets',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('bruteforce', 'Bruteforce Attack')], max_length=128)),
                ('description', models.TextField(blank=True)),
                ('time_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('object', models.ForeignKey(help_text='Target of the attack', on_delete=django.db.models.deletion.PROTECT, to='incidents.incidenttarget')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='CommonVulnerabilityExposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_number', models.CharField(max_length=64)),
                ('cna_reference', models.CharField(max_length=256)),
                ('incidents', models.ManyToManyField(blank=True, db_table='incident_cves', related_name='cve_objects', to='incidents.incident')),
            ],
            options={
                'db_table': 'cves',
            },
        ),
    ]
